### ISSUE TITLE
Error when running in Docker ruby:2.4

### ISSUE THREAD

**Issue by gabro** [dbgrandi/danger-proselint#18]
I'm trying this on Drone CI using this configuration:

```yaml
build:
  prose-lint:
    image: ruby:2.4
    environment:
      DANGER_GITHUB_API_TOKEN: $$BOT_GITHUB_TOKEN
    commands:
      - bundle install
      - bundle exec danger
```

which simply specifies to run `bundle install` and `bundle exec danger` in the `ruby:2.4` docker image.

The Gemfile looks like:

```ruby
source "https://rubygems.org"

gem "danger"
gem "danger-prose"
```

and the Dangerfile is:

```ruby
prose.check_spelling "posts/*.md"
```

This is the error I get:

```
$ bundle exec danger
[!] The exception involves the following plugins:
-  danger-prose
bundler: failed to load command: danger (/usr/local/bundle/bin/danger)
Danger::DSLError: 
[!] Invalid `Dangerfile` file: mdspell is not in the user's PATH, or it failed to install
#  from Dangerfile:1
#  -------------------------------------------
>  prose.check_spelling "posts/*.md"
#  -------------------------------------------
```

<details>
 <summary>Here's the full CI log, including the install phase</summary>

```
$ bundle install
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Fetching claide 1.0.1
Installing claide 1.0.1
Fetching colored2 3.1.2
Installing colored2 3.1.2
Fetching nap 1.1.0
Installing nap 1.1.0
Fetching open4 1.3.4
Installing open4 1.3.4
Fetching multipart-post 2.0.0
Installing multipart-post 2.0.0
Fetching git 1.3.0
Installing git 1.3.0
Fetching kramdown 1.13.2
Installing kramdown 1.13.2
Fetching public_suffix 2.0.5
Installing public_suffix 2.0.5
Fetching unicode-display_width 1.2.1
Installing unicode-display_width 1.2.1
Using bundler 1.15.0
Fetching cork 0.3.0
Installing cork 0.3.0
Fetching faraday 0.12.1
Installing faraday 0.12.1
Fetching addressable 2.5.1
Installing addressable 2.5.1
Fetching terminal-table 1.8.0
Installing terminal-table 1.8.0
Fetching claide-plugins 0.9.2
Installing claide-plugins 0.9.2
Fetching faraday-http-cache 1.3.1
Installing faraday-http-cache 1.3.1
Fetching sawyer 0.8.1
Installing sawyer 0.8.1
Fetching octokit 4.7.0
Installing octokit 4.7.0
Fetching danger 5.2.2
Installing danger 5.2.2
Fetching danger-prose 2.0.4
Installing danger-prose 2.0.4
Bundle complete! 2 Gemfile dependencies, 20 gems now installed.
Bundled gems are installed into /usr/local/bundle.
$ bundle exec danger
[!] The exception involves the following plugins:
-  danger-prose
bundler: failed to load command: danger (/usr/local/bundle/bin/danger)
Danger::DSLError: 
[!] Invalid `Dangerfile` file: mdspell is not in the user's PATH, or it failed to install
#  from Dangerfile:1
#  -------------------------------------------
>  prose.check_spelling "posts/*.md"
#  -------------------------------------------

 /usr/local/bundle/gems/danger-prose-2.0.4/lib/danger_plugin.rb:120:in `check_spelling'
 Dangerfile:1:in `block in parse'
 /usr/local/bundle/gems/danger-5.2.2/lib/danger/danger_core/dangerfile.rb:199:in `eval'
 /usr/local/bundle/gems/danger-5.2.2/lib/danger/danger_core/dangerfile.rb:199:in `block in parse'
 /usr/local/bundle/gems/danger-5.2.2/lib/danger/danger_core/dangerfile.rb:195:in `instance_eval'
 /usr/local/bundle/gems/danger-5.2.2/lib/danger/danger_core/dangerfile.rb:195:in `parse'
 /usr/local/bundle/gems/danger-5.2.2/lib/danger/danger_core/dangerfile.rb:272:in `run'
 /usr/local/bundle/gems/danger-5.2.2/lib/danger/danger_core/executor.rb:27:in `run'
 /usr/local/bundle/gems/danger-5.2.2/lib/danger/commands/runner.rb:66:in `run'
 /usr/local/bundle/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
 /usr/local/bundle/gems/danger-5.2.2/bin/danger:5:in `<top (required)>'
 /usr/local/bundle/bin/danger:17:in `load'
 /usr/local/bundle/bin/danger:17:in `<top (required)>'
```

</details>

Any idea of what may be causing the issue?

**Comment by dbgrandi** [comment]
Looks like `mdspell` did not get installed, or if it did is not in the PATH.

https://github.com/dbgrandi/danger-prose/blob/master/lib/danger_plugin.rb#L117

Can you manually (well, in CI) run:

```
npm install -g orta/node-markdown-spellcheck
```

and then

```
which mdspell
```

**Comment by dbgrandi** [comment]
That could fail on Drone if you don't have permissions to install `orta/node-markdown-spellcheck` globally. Could also try without the `-g`

**Comment by gabro** [comment]
The real problem in that case would be the availability of `node`/`npm` in the ruby docker image.

Is bundler supposed to install the node package too? Where's the step? Maybe I can debug why it's not in the current path

**Comment by gabro** [comment]
Oh, found it: https://github.com/dbgrandi/danger-prose/blob/master/lib/danger_plugin.rb#L117

So this plugin assumes a ruby + node environment for spellchecking and a ruby + python environment for linting. No wonders it fails on a ruby-only image :) I'll try to throw node and python in the mix and see what happens.

**Comment by gabro** [comment]
Cool, using a docker image with node/ruby/python ([this one](https://hub.docker.com/r/phusion/passenger-full), specifically) it worked :) 

I would add a pre-requisites section in the README, because I didn't expect to be needing python and node as well.

**Comment by dbgrandi** [comment]
Good idea! Finally getting around to adding this after weeks of shirking responsibility. :)

It's over at https://github.com/dbgrandi/danger-prose/pull/22
